### PR TITLE
WIP: a few changes for RemoteGallery

### PR DESCRIPTION
**Pull request by mjholgate**
RemoteGallery is excellent - just what I was looking for!

I thought I'd have a go at hacking a bit on it, and I've a got a few changes which might be of interest (probably not quite ready to pull just yet, but almost there).

1) the main change uses 'jhead' on the server to extract the JPEG thumbnail from image files before fetching the 'full quality' version. I was finding that large directories would take a long time to populate the list (imagemagick was taking a long time to run). This change speeds up population of the list significantly for slow servers on fast network connections (at the expense of more fetches in total). Perhaps this should be an option, rather than always on? We fallback to the generated thumbnail if there is no embedded thumbnail.

2) a fix a bug where we never fetch images on the ImageSlider view if we didn't
start fetching them on the RemoteBrowser activity.

3) prevent infinite looping if a fetch fails.

Let me know if these changes are useful for you!

### CODE REVIEW

**Comment by mjholgate** [comment]
Issues still to be resolved:

1) Thumbnails can have wrong orientation (auto-orient)
2) Might be nice to prioritise fetch of high quality versions of images when in ImageSlider view.

**Comment by cachapa** [comment]
Hey Matt,

thanks for your offer to help.
I'm very excited to get help improve Remote Gallery. Honestly I still
have a lot of ideas for new things, but I'm very busy these days and
can't devote any time to development there.

In any case I was happy to read that your ideas seem to be in the same
direction as mine.
My replies are below:

> 1) the main change uses 'jhead' on the server to extract the JPEG thumbnail from image files before fetching the 'full quality' version. I was finding that large directories would take a long time to populate the list (imagemagick was taking a long time to run). This change speeds up population of the list significantly for slow servers on fast network connections (at the expense of more fetches in total). Perhaps this should be an option, rather than always on? We fallback to the generated thumbnail if there is no embedded thumbnail.

This is actually how RE originally worked. It'd request the thumbnails
only first.
The problem is that ImageMagick was as slow generating thumbails as it
was generating the "full" versions (my server is a lowly Atom).
In the end I decided to simply send the full image and generate the
thumbail in the phone. Populating a directory was just as fast, but
the full version would be already there.
I didn't know about jhead. If it works faster, then I'm all for it.

Another issue with dir population is that a new SSH process is
launched for downloading each image. It simplified coding somewhat as
it saved me from implementing a complete session management system.
On the other hand, it's an inneficient way to download a lot of images.

I'd love to find a way to reuse a given connection. It might be
possible to start small and use it only for the thumbnails, and once
it's working, use it also for other things (getting the dir list,
getting the images themselves, etc.).

> 2) a fix a bug where we never fetch images on the ImageSlider view if we didn't
> start fetching them on the RemoteBrowser activity.

I'll need to look at this.
The reason it doesn't ask to download from the ImageSlider is because
you usually have to go through the RemoteBrowser in order to reach it.
If there is anything to download, the RB activity should start working
on it, and I didn't want two concurrent processes downloading the same
image -- first because it's wasting resources, and second because it
might corrupt the images (not sure though).

> 3) prevent infinite looping if a fetch fails.

Oh yeah :-)
What was your solution?

As for your code, I'm having a very hard weekend. I'm moving
appartments and at the same time working around the clock to finish my
thesis.
I don't really have any brain cells left to look at code, but I'll try
to do it during the next few days and merge (unless I find something
out of the ordinary :-)

Cheers,

## 

Daniel Cachapa

**Comment by mjholgate** [comment]
On 26/02/2012 22:12, cachapa wrote:

> Hey Matt,
> 
> thanks for your offer to help.
> I'm very excited to get help improve Remote Gallery. Honestly I still
> have a lot of ideas for new things, but I'm very busy these days and
> can't devote any time to development there.

No problem - don't worry - I know the feeling. With a programming day 
job, I only get time to play around with other projects here and there :(.

> This is actually how RE originally worked. It'd request the thumbnails
> only first.
> The problem is that ImageMagick was as slow generating thumbails as it
> was generating the "full" versions (my server is a lowly Atom).
> In the end I decided to simply send the full image and generate the
> thumbail in the phone. Populating a directory was just as fast, but
> the full version would be already there.
> I didn't know about jhead. If it works faster, then I'm all for it.

jhead extracts the embedded thumbnail from the jpeg, so is very fast to 
run (the thumbnail is just a second JPEG image within the file). My 
server is an Atom too, and I saw a big performance increase for the 
directory view.

The downside is that not all JPEGs contain thumbnails - however, most 
digital cameras do add one, so in most cases it is a fairly big win. For 
those that don't, we still downsize the large image on the phone as before.

My current implementation is not ideal though, as it will fetch _all_ 
thumbnails in a directory before it fetches the full size version (even 
when viewing in the image slider view). It would probably be best to 
fetch the full size version much sooner especially in the image slider 
view (perhaps we could fetch a few thumbnails before and after the 
current image, then fetch the full size version). I'll perhaps have a 
play with this when I get more time.

Another downside to my approach is that it is does use more data 
overall. I think it's probably worth it though.

> Another issue with dir population is that a new SSH process is
> launched for downloading each image. It simplified coding somewhat as
> it saved me from implementing a complete session management system.
> On the other hand, it's an inneficient way to download a lot of images.
> 
> I'd love to find a way to reuse a given connection. It might be
> possible to start small and use it only for the thumbnails, and once
> it's working, use it also for other things (getting the dir list,
> getting the images themselves, etc.).

Yeah, I was wondering about this, and was thinking about how it could be 
done, and yes, it does seem quite tricky!

The bit I was most unsure about was how to parse the output - to 
determine where one image ended and the next began. I have a few ideas 
so will think about this a bit more.

One related issue that I noticed is that (at least on Ice Cream 
Sandwich), is that despite creating multiple async tasks, they get 
executed serially.

I think this is a change that Google made in later Android versions, but 
it really hampers performance. A small tweak to the way the task is 
started would allow us to run them in parallel again.

> > 2) a fix a bug where we never fetch images on the ImageSlider view if we didn't
> > start fetching them on the RemoteBrowser activity.
> 
> I'll need to look at this.
> The reason it doesn't ask to download from the ImageSlider is because
> you usually have to go through the RemoteBrowser in order to reach it.
> If there is anything to download, the RB activity should start working
> on it, and I didn't want two concurrent processes downloading the same
> image -- first because it's wasting resources, and second because it
> might corrupt the images (not sure though).

Yeah - all I do here is allow the RemoteBrowser to continue fetching the 
images. The problem was that because only a single 'download complete' 
listener was allowed, the RB would not queue new images for fetching 
when the previous ones had completed. So it was only an issue if you 
entered the ImageSlider viewer and there were many images still unfetched.

> > 3) prevent infinite looping if a fetch fails.
> 
> Oh yeah :-)
> What was your solution?

I just added a boolean (well, two actually - one for thumbnail, the 
other for the main image), and set that after attempting a fetch. I then 
wouldn't try and fetch that image again (unless a new RemoteBrowser for 
that folder was opened).

This turned out to be very necessary with the new thumbnail code -  some 
JPEGs do not contain embedded thumbnails, and I need to make sure we 
didn't try and fetch them in a loop. It's probably much less of an issue 
with just the regular fetch which should rarely fail.

> As for your code, I'm having a very hard weekend. I'm moving
> appartments and at the same time working around the clock to finish my
> thesis.
> I don't really have any brain cells left to look at code, but I'll try
> to do it during the next few days and merge (unless I find something
> out of the ordinary :-)

No rush. I'm not entirely happy with my code just yet - it'd be good to 
address some of the issues I've mentioned above. I really just wanted to 
give you an initial 'ping' to see if you were interested. I'm really 
pleased you are - RemoteGallery is excellent, and is _exactly_ what I've 
been looking for for a long time - wish I'd found it sooner!

Good look with the apartment move and the thesis writing, and thanks for 
getting in touch!

Matt.

**Comment by cachapa** [comment]
> jhead extracts the embedded thumbnail from the jpeg, so is very fast to
> run (the thumbnail is just a second JPEG image within the file). My
> server is an Atom too, and I saw a big performance increase for the
> directory view.

Sounds good.

> My current implementation is not ideal though, as it will fetch _all_
> thumbnails in a directory before it fetches the full size version (even
> when viewing in the image slider view). It would probably be best to
> fetch the full size version much sooner especially in the image slider
> view (perhaps we could fetch a few thumbnails before and after the
> current image, then fetch the full size version). I'll perhaps have a
> play with this when I get more time.

I also don't know what is the best strategy. Usually these things
become obvious with usage, so I guess we'll have to simply try.

> Another downside to my approach is that it is does use more data
> overall. I think it's probably worth it though.

Thumbnails should be small enough not to make a difference, at least
not next to a directory full of medium resolution images.

> Yeah, I was wondering about this, and was thinking about how it could be
> done, and yes, it does seem quite tricky!
> 
> The bit I was most unsure about was how to parse the output - to
> determine where one image ended and the next began. I have a few ideas
> so will think about this a bit more.

I think it's easy to listen for the end of the stream. As far as I
remember, RG already does this in order to close the connection.

> One related issue that I noticed is that (at least on Ice Cream
> Sandwich), is that despite creating multiple async tasks, they get
> executed serially.

That may explain why RG loads slower on this phone. I thought it was just me.

> No rush. I'm not entirely happy with my code just yet - it'd be good to
> address some of the issues I've mentioned above. I really just wanted to
> give you an initial 'ping' to see if you were interested. I'm really
> pleased you are - RemoteGallery is excellent, and is _exactly_ what I've
> been looking for for a long time - wish I'd found it sooner!
> 
> Good look with the apartment move and the thesis writing, and thanks for
> getting in touch!

Turns out that because of the apartment move I won't be able to test
RG for a quite some time (no internet at home, so the server is
offline).
So I did the next best thing: I looked at your changes, and they look good.
I'll merge (as soon as I find out how -- it's my first merge on
GitHub) so that we can move forward.

## 

Daniel Cachapa

**Pull request merged**
